# Generated by Django 2.2.16 on 2020-11-23 18:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_auto_20201121_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 25, 18, 40, 57, 725323, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
